name: dbt CI Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: ""
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

  dbt-build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dbt package dependencies
        run: |
          . venv/bin/activate
          dbt deps
      - name: Copy profiles.yml to /home/runner/.dbt
        run: |
          mkdir -p /home/runner/.dbt
          cp ./profiles.yml /home/runner/.dbt/profiles.yml
      - name: Compile dbt build (CI)
        run: |
          . venv/bin/activate
          dbt build --target ci
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
